"""
AI Agents Module
Guru-level trading intelligence with institutional-grade analysis
"""

from .guru_prompts import (
    FOREX_GURU_PROMPT,
    CRYPTO_GURU_PROMPT,
    STOCK_GURU_PROMPT,
    COMMODITY_GURU_PROMPT,
    INDEX_GURU_PROMPT,
    MULTI_TIMEFRAME_ANALYSIS,
    SMART_MONEY_CONCEPTS,
    RISK_MANAGEMENT_RULES
)

__all__ = [
    'FOREX_GURU_PROMPT',
    'CRYPTO_GURU_PROMPT',
    'STOCK_GURU_PROMPT',
    'COMMODITY_GURU_PROMPT',
    'INDEX_GURU_PROMPT',
    'MULTI_TIMEFRAME_ANALYSIS',
    'SMART_MONEY_CONCEPTS',
    'RISK_MANAGEMENT_RULES'
]
